on:
  workflow_call:
    inputs:
      terraform_directory:
        type: string
        required: false
        default: ./tf

jobs:
  terraform_validate:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          mask-aws-account-id: true
          role-duration-seconds: 900
          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE }}
          role-session-name: gha-lad-${{ github.run_id }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Validate
        working-directory: ${{ inputs.terraform_directory }}
        run: |
          terraform init -upgrade
          terraform validate

  terraform_plan:
    runs-on: ubuntu-latest
    needs: 
      - terraform_validate
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          mask-aws-account-id: true
          role-duration-seconds: 900
          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE }}
          role-session-name: gha-lad-${{ github.run_id }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Plan
        working-directory: ${{ inputs.terraform_directory }}
        run: |
          terraform init -upgrade
          terraform validate
          terraform plan -out ../tfplan

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: terraform_plan
          path: tfplan
        
  terraform_deploy:
    runs-on: ubuntu-latest
    needs: 
      - terraform_plan
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          mask-aws-account-id: true
          role-duration-seconds: 900
          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE }}
          role-session-name: gha-lad-${{ github.run_id }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: terraform_plan

      - name: Terraform Apply
        working-directory: ${{ inputs.terraform_directory }}
        run: |
          terraform init -upgrade
          terraform apply ../tfplan
