on:
    workflow_call:
      inputs:
        package:
          type: string
          required: true
          default: dev
        dotnet_version:
          type: string
          default : '8.0'
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version}}

      - name: Package
        run: dotnet pack

      - name: Publish
        run: |
          dotnet nuget push ./${{ inputs.package }}/bin/Release/*.nupkg  \
            -k ${{ secrets.NUGET_TOKEN }} \
            -s https://api.nuget.org/v3/index.json \
            --skip-duplicate