on:
  workflow_call:
    inputs:
      runs_on:
        type: string
        required: false
        default: ubuntu-latest
      region:
        type: string
        required: false
        default: us-east-2
      environment:
        type: string
        required: true
      terraform_directory:
        type: string
        required: false
        default: ./tf

jobs:
  terraform_plan:
    runs-on: ${{ inputs.runs_on }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          mask-aws-account-id: true
          role-duration-seconds: 900
          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE }}
          role-session-name: gha-${{ github.run_id }}
          aws-region: ${{ inputs.region || 'us-east-2' }}

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v4
      
      - name: Setup Terraform Variables
        working-directory: ${{ inputs.terraform_directory }}
        run: |
          echo "image_tag = \"${{ github.ref_name }}\"" >> ${{ inputs.environment }}.tfvars
  
      - name: Terraform Plan
        working-directory: ${{ inputs.terraform_directory }}
        run: |
          terraform init -backend-config="./backend/${{ inputs.environment }}.tfbackend"
          terraform validate
          terraform plan -input=false -var-file="./${{ inputs.environment }}.tfvars" -out ./final.tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-${{ inputs.environment }}
          path: ${{ inputs.terraform_directory }}/final.tfplan
          if-no-files-found: error
          retention-days: 1

  terraform_apply:
    needs: terraform_plan
    runs-on: ${{ inputs.runs_on }}
    permissions:
      id-token: write
      contents: read
    if: github.event_name == 'workflow_dispatch' || github.ref_name == 'master'
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          mask-aws-account-id: true
          role-duration-seconds: 900
          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE }}
          role-session-name: gha-${{ github.run_id }}
          aws-region: ${{ inputs.region || 'us-east-2' }}

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v4

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan-${{ inputs.environment }}
          path: ${{ inputs.terraform_directory }}

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' || github.ref_name == 'master'
        working-directory: ${{ inputs.terraform_directory }}
        run: |
          terraform init -backend-config="./backend/${{ inputs.environment }}.tfbackend"
          terraform apply -auto-approve ./final.tfplan
